In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
np.arrange(15)

AttributeError: 'module' object has no attribute 'arrange'

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(15,45)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [7]:
np.empty((2,3,2))

array([[[  9.36820400e-317,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [12]:
for x in np.arange(1,50):
    if x%2 != 0:
        print(x)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


In [14]:
count = 0
for x in np.arange(1,50):
    if x%2 != 0:
        count = count + 1
np.zeros(count)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr = np.array(data1, dtype=np.int32)

In [16]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr1 = arr + arr 
print(arr1)
print('---'*10)
arr * 5 

[[  2.   4.   6.]
 [  8.  10.  12.]]
------------------------------


array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:3, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [19]:
arr = np.arange(10)  
arr[arr.size-5:arr.size]

array([5, 6, 7, 8, 9])

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[arr.size-5:arr.size] = 41

In [22]:
arr

array([ 0,  1,  2,  3,  4, 41, 41, 41, 41, 41])

In [23]:
arr + 1

array([ 1,  2,  3,  4,  5, 42, 42, 42, 42, 42])

In [24]:
arr[arr >= 40] = 50

In [25]:
arr

array([ 0,  1,  2,  3,  4, 50, 50, 50, 50, 50])

In [29]:
for id, x in enumerate(arr):
    if id%5 == 0:
        print(x)

0
50


In [31]:
zarr1 = [1,2, 3, 4,5,6, 7, 8, 9, 10,1,2, 3, 4,5,6, 7, 8, 9, 10,1,2,3,4,5]
zarr = np.array(zarr)
zarr.reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [38]:
for j in range(5):
    for i in range(5):
        zarr[j][i] = j

TypeError: 'numpy.int64' object does not support item assignment

In [36]:
zarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])